[build]
  command = "npx vite build --config vite.netlify.config.js"
  publish = "dist"
  functions = "server"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@babel/preset-typescript", "lightningcss"]

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[build.processing]
  skip_processing = false

[build.processing.js]
  bundle = true
  minify = true

[build.processing.css]
  bundle = true
  minify = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200